[phases.install]
cmds = ["npm install --legacy-peer-deps && npm install -g serve"]

[phases.build]
cmds = ["node ./node_modules/react-scripts/bin/react-scripts.js build"]

[start]
cmd = "serve -s build -l 3000"
